FROM centos:centos7
MAINTAINER Amit Bakshi <ambakshi@gmail.com>

RUN rpm -Uvh http://mirror.pnl.gov/epel/7/x86_64/e/epel-release-7-1.noarch.rpm
RUN yum clean all && yum update -y
RUN yum install --enablerepo='*' -y vim-enhanced sudo tar coreutils git ctags-etags \
        expect ruby-devel gcc glibc-devel python-devel java-1.7.0-openjdk-headless
RUN rpm --nodeps -Uvh http://gii-repo.int.funzio.com/gree-centos-6/x86_64/gii-ec2-tools-1.0-8.x86_64.rpm \
        http://gii-repo.int.funzio.com/gree-centos-6/x86_64/gree-go-1.3.1-7.el6.x86_64.rpm \
        http://gii-repo.int.funzio.com/gree-centos-6/noarch/aws-apitools-common-1.1.0-1.8.amzn1.noarch.rpm \
        http://gii-repo.int.funzio.com/gree-centos-6/noarch/aws-apitools-ec2-1.7.1.0-1.2.amzn1.noarch.rpm \
        http://gii-repo.int.funzio.com/gree-centos-6/noarch/aws-apitools-as-1.0.61.6-1.0.amzn1.noarch.rpm \
        http://gii-repo.int.funzio.com/gree-centos-6/noarch/aws-apitools-mon-1.0.20.0-1.0.amzn1.noarch.rpm
RUN echo "%wheel	ALL=(ALL)	NOPASSWD: ALL" > /etc/sudoers.d/wheel && chmod 0400 /etc/sudoers.d/wheel
RUN sed -i "s/^%wheel/# %wheel/g" /etc/sudoers
RUN yum install -y docker screen git-all mercurial
RUN curl -sSL -O https://get.docker.io/builds/Linux/x86_64/docker-1.2.0 && chmod +x docker-1.2.0 && mv docker-1.2.0 /usr/local/bin/docker
RUN rpm -Uvh http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
RUN yum install -y puppet facter

## VO//LUME ["/target","/data"]

RUN curl -fsSL https://storage.googleapis.com/golang/go1.3.1.linux-amd64.tar.gz | tar zxf - -C /usr/local

RUN groupadd -g 1111 staff
RUN useradd --create-home --shell /bin/bash -g staff -G wheel --uid 1000 dev

ENV HOME /home/dev
ENV GOPATH /home/dev/go
ENV PATH /usr/local/go/bin:$PATH

RUN ln -s /usr/share/git-core/contrib/completion/git-prompt.sh /etc/bash_completion.d
RUN mkdir -p /home/dev/go/src /home/dev/.vim/bundle /home/dev/bin
RUN git clone -q https://github.com/gmarik/Vundle.vim.git /home/dev/.vim/bundle/Vundle.vim

# Make empty file or it'll be owned by root
RUN mkdir -p /var/shared/RUN && touch /var/shared/placeholder
RUN chown -R dev:staff /var/shared
VOLUME /var/shared

RUN ln -s /var/shared/.ssh /home/dev/.ssh
RUN ln -s /var/shared/.bash_history /home/dev/.bash_history

RUN echo '[ -n "$PS1" ] && PS1="[\[\033[32m\]\u@\h\[\033[00m\] \[\033[36m\]\W\[\033[31m\]$(__git_ps1)\[\033[00m\]]\n\$ "' >> /home/dev/.bashrc
ADD .gitconfig.local /home/dev/.gitconfig.local
ADD gitconfig /home/dev/.gitconfig
ADD vimrc /home/dev/.vimrc
#ADD bash_profile /home/dev/.bash_profile
RUN vim /home/dev/.vimrc -c ':PluginInstall' -c ':qa!'

RUN chown -R dev:staff /home/dev
WORKDIR /home/dev
USER dev
